### ISSUE TITLE
foutbericht instance niet definieren als uri

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-common#113]
in Foutbericht wordt instance gedefinieerd als format: uri:
```
        instance:
          type: string
          format: uri
          description: Uri van de aanroep die de fout heeft veroorzaakt
```

hierdoor is een relatieve url niet toegestaan, althans niet volgens sommige tooling, zoals Postman.

In Href voor andere links hebben we daarom format: uri verwijderd. Ik denk dat we dat hier ook zouden moeten doen.

@MelvLee @JohanBoer Is dat een breaking change wanneer we dat zouden doorvoeren op een bestaande api?
