### ISSUE TITLE
definities common.yaml voldoen niet aan DD5.3

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-common#77]
> ### DD5.3 Technische definities van properties alleen opnemen voor zover dat noodzakelijk is voor gebruik
> Meestal volstaat het om in de definitie van properties in de response de _propertynaam, type, format, description_ en _example_ op te nemen.
> We gebruiken daar niet de technische definities _pattern, minimum, maximum, minLength, maxLength, minItems_ en _required_, tenzij....

- gebruik minimum en maximum in Datum_onvolledig dag, maand en jaar.
- minItems en maxItems in de geoJson definities

N.B. waarom zitten geoJson componenten in common.yaml? In BAG en BRK verwijzen we naar definities van opengis , niet naar common.yaml. Volgens mij kunnen die verwijderd worden uit common.yaml

N.B. we kunnen regel toevoegen aan spectral lint om DD5.3 te testen:

```
  too-much-information:
    description: properties of GET responses should not use pattern, minimum, maximum, minLength, maxLength, minItems or required
    resolved: false
    type: style
    message: 'Gebruik geen {{property}} in response definitie: {{path}}'
    given: '$.components.schemas..properties[*]'
    then:
      - field: "minItems"
        function: falsy

      - field: "maxItems"
        function: falsy

      - field: "maxLength"
        function: falsy

      - field: "maxLength"
        function: falsy

      - field: "minimum"
        function: falsy

      - field: "maximum"
        function: falsy

      - field: "required"
        function: falsy

      - field: "pattern"
        function: falsy
```
